# Generated by Django 4.1.1 on 2023-01-25 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iot", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="secfile", name="sec_file", field=models.FileField(upload_to=""),
        ),
    ]
