# Generated by Django 4.1.1 on 2023-02-02 02:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("phone_number", models.CharField(max_length=20, unique=True)),
                ("email", models.EmailField(max_length=255, unique=True)),
                ("car_number", models.CharField(max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("is_admin", models.BooleanField(default=False)),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="Parking",
            fields=[
                (
                    "parking_number",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("lat", models.CharField(max_length=20)),
                ("lon", models.CharField(max_length=20)),
                ("res_state", models.CharField(max_length=20)),
                ("detail_add", models.CharField(blank=True, max_length=255, null=True)),
                ("finish_car_number", models.CharField(max_length=20, null=True)),
                ("parking_car_number", models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Res",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.CharField(max_length=20)),
                ("end_time", models.CharField(max_length=100)),
                ("parking_car_number", models.CharField(max_length=20)),
                (
                    "parking_number",
                    models.ForeignKey(
                        blank=True,
                        db_column="parking_number",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="common.parking",
                    ),
                ),
                (
                    "phone_number",
                    models.ForeignKey(
                        blank=True,
                        db_column="phone_number",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="parking_number",
            field=models.ForeignKey(
                blank=True,
                db_column="parking_number",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="common.parking",
            ),
        ),
    ]
