# Generated by Django 4.1.1 on 2023-02-02 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="res", old_name="parking_car_number", new_name="res_car_number",
        ),
    ]
