# Generated by Django 4.1.1 on 2023-02-02 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_rename_parking_car_number_res_res_car_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parking",
            name="parking_number",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
