# Generated by Django 4.1.1 on 2023-02-03 01:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0004_alter_parking_finish_car_number_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="parking_number",),
        migrations.AddField(
            model_name="parking",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
