# Generated by Django 4.1.1 on 2023-02-04 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0007_alter_parking_owner_alter_parking_parking_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="res", old_name="phone_number", new_name="user_id",
        ),
        migrations.RemoveField(model_name="parking", name="parking_car_number",),
    ]
