# Generated by Django 4.1.1 on 2023-02-05 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0008_rename_phone_number_res_user_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="res",
            name="start_time",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
