# Generated by Django 4.1.1 on 2023-02-05 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0009_res_start_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="res", name="start_time", field=models.CharField(max_length=100),
        ),
    ]
