# Generated by Django 4.1.1 on 2023-02-07 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0011_alter_res_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="res", name="end_time", field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="res", name="start_time", field=models.DateTimeField(),
        ),
    ]
